/** CENTROCONOCIMIENTO.JS · Biblioteca interna, versiones y multimedia. */
window.CentroConocimiento={
 estado:{pagina:1,tipo:"TODOS",busqueda:"",documentos:[],hayMas:false,puedeEditar:false,roles:[],manualExpandido:false},
 sesion(){return window.Sistema&&Sistema.obtenerSesion?Sistema.obtenerSesion():JSON.parse(localStorage.getItem("sesion")||sessionStorage.getItem("sesion")||"{}");},
 async cargar(opciones){
  opciones=opciones||{};this.estado.pagina=1;this.estado.documentos=[];
  this.pintarBase();await this.buscar(false);
  if(opciones.documentoId)await this.abrirDocumento(opciones.documentoId);
 },
 pintarBase(){
  const c=document.querySelector("main.contenido");if(!c)return;
  c.innerHTML=`<section class="cc-modulo"><header class="cc-hero"><div><span>CENTRO DE CONOCIMIENTO</span><h1>Biblioteca institucional</h1><p>Políticas, procedimientos, manuales y tutoriales disponibles para su rol.</p></div><button id="ccNuevo" type="button" hidden><i class="fa-solid fa-plus"></i> Nuevo contenido</button></header><div class="cc-barra"><label class="cc-buscar"><i class="fa-solid fa-magnifying-glass"></i><input id="ccBuscar" placeholder="Buscar por título, categoría o palabra clave"></label><select id="ccTipo" aria-label="Filtrar por tipo"><option value="TODOS">Todo el contenido</option><option>MANUAL</option><option>POLITICA EMPRESA</option><option>POLITICA ALMACEN PT</option><option>PROCEDIMIENTO</option><option>TUTORIAL</option></select></div><div class="cc-biblioteca"><aside class="cc-navegacion"><strong>Documentación</strong><button type="button" data-cc-tipo="TODOS" class="activo"><i class="fa-solid fa-layer-group"></i><span>Todo</span></button><button type="button" data-cc-tipo="MANUAL"><i class="fa-solid fa-book"></i><span>Manuales</span></button><button type="button" data-cc-tipo="POLITICA EMPRESA"><i class="fa-solid fa-building-shield"></i><span>Políticas de empresa</span></button><button type="button" data-cc-tipo="POLITICA ALMACEN PT"><i class="fa-solid fa-warehouse"></i><span>Políticas de Almacén PT</span></button><button type="button" data-cc-tipo="PROCEDIMIENTO"><i class="fa-solid fa-list-check"></i><span>Procedimientos</span></button><button type="button" data-cc-tipo="TUTORIAL"><i class="fa-solid fa-circle-play"></i><span>Tutoriales</span></button></aside><section class="cc-listado"><header><div><strong>Contenido disponible</strong><span id="ccResumen" class="cc-resumen"></span></div><span class="cc-indicacion">Seleccione una fila para consultar</span></header><div class="cc-columnas"><span>Documento</span><span>Tipo</span><span>Versión</span><span>Estado</span><span></span></div><div id="ccCatalogo" class="cc-catalogo"></div><button id="ccCargarMas" class="cc-cargar-mas" type="button" hidden><i class="fa-solid fa-plus"></i> Cargar más</button></section></div></section>`;
  document.getElementById("ccBuscar").oninput=this.debounce(()=>{this.estado.busqueda=document.getElementById("ccBuscar").value;this.buscar(false);},350);
  document.getElementById("ccTipo").onchange=e=>{this.estado.tipo=e.target.value;document.querySelectorAll("[data-cc-tipo]").forEach(x=>x.classList.toggle("activo",x.dataset.ccTipo===this.estado.tipo));this.buscar(false);};
  document.getElementById("ccCargarMas").onclick=()=>this.buscar(true);
  document.querySelectorAll("[data-cc-tipo]").forEach(b=>b.onclick=()=>{this.estado.tipo=b.dataset.ccTipo;document.getElementById("ccTipo").value=this.estado.tipo;document.querySelectorAll("[data-cc-tipo]").forEach(x=>x.classList.toggle("activo",x===b));this.buscar(false);});
 },
 async buscar(acumular){
  const pagina=acumular?this.estado.pagina+1:1;this.cargarEspera("Consultando conocimiento","Aplicando permisos y filtros.");
  try{const r=await API.post({action:"obtenerCentroConocimiento",pagina,limite:12,tipo:this.estado.tipo,busqueda:this.estado.busqueda});if(!r||!r.ok)throw new Error(r&&r.mensaje||"No fue posible cargar el centro.");const d=r.data||{};this.estado.documentos=acumular?this.estado.documentos.concat(d.documentos||[]):d.documentos||[];this.estado.pagina=d.pagina||pagina;this.estado.hayMas=!!d.hayMas;this.estado.puedeEditar=!!d.puedeEditar;this.estado.roles=d.roles||[];this.render();}catch(e){Sistema.error(e.message);}finally{this.ocultarEspera();}
 },
 render(){
  const docs=this.estado.documentos,resumen=document.getElementById("ccResumen"),catalogo=document.getElementById("ccCatalogo"),mas=document.getElementById("ccCargarMas"),nuevo=document.getElementById("ccNuevo");if(!catalogo)return;
  const esSeccion=d=>/^CC-MANUAL-0[2-9]$/i.test(String(d.ID_Documento||"")),maestro=docs.find(d=>String(d.ID_Documento)==="CC-MANUAL-01"),secciones=docs.filter(esSeccion),buscando=String(this.estado.busqueda||"").trim().length>0,filtroEspecifico=!['TODOS','MANUAL'].includes(this.n(this.estado.tipo));
  const visibles=buscando||filtroEspecifico?docs:docs.filter(d=>!esSeccion(d));
  resumen.textContent=`${visibles.length} contenido${visibles.length===1?"":"s"} visible${visibles.length===1?"":"s"}`;nuevo.hidden=!this.estado.puedeEditar;nuevo.onclick=()=>this.editarDocumento();mas.hidden=!this.estado.hayMas;
  catalogo.innerHTML=visibles.map(d=>String(d.ID_Documento)==="CC-MANUAL-01"?this.filaManual(d,secciones):this.filaDocumento(d)).join("")||`<div class="cc-vacio"><i class="fa-regular fa-folder-open"></i><strong>No hay contenido para este filtro</strong><span>Pruebe otra búsqueda o categoría.</span></div>`;
  catalogo.querySelectorAll("[data-cc-id]").forEach(x=>x.onclick=e=>{e.stopPropagation();this.abrirDocumento(x.dataset.ccId);});
  const toggle=catalogo.querySelector("[data-cc-toggle-manual]");if(toggle)toggle.onclick=e=>{e.stopPropagation();this.estado.manualExpandido=!this.estado.manualExpandido;this.render();};
 },
 filaDocumento(d){return `<button type="button" class="cc-fila ${Number(d.Destacado)?"destacado":""}" data-cc-id="${this.e(d.ID_Documento)}"><span class="cc-documento"><i class="fa-solid ${this.icono(d.Tipo)}"></i><span><strong>${this.e(d.Titulo)}</strong><small>${this.e(d.Resumen)}</small><em>${this.e(d.Categoria)}</em></span></span><span class="cc-tipo">${this.e(this.etiquetaTipo(d.Tipo))}</span><span class="cc-version"><i class="fa-solid fa-code-branch"></i> ${this.e(d.Version_Actual)}</span><span class="cc-estado ${this.n(d.Estado).toLowerCase()}">${this.e(d.Estado)}</span><i class="fa-solid fa-chevron-right cc-abrir"></i></button>`;},
 filaManual(d,secciones){const abierto=this.estado.manualExpandido,capitulos=secciones.length?secciones.map((x,i)=>`<button type="button" data-cc-id="${this.e(x.ID_Documento)}"><span>${String(i+1).padStart(2,"0")}</span><span><strong>${this.e(x.Titulo)}</strong><small>${this.e(x.Resumen||x.Categoria)}</small></span><i class="fa-solid fa-chevron-right"></i></button>`).join(""):`<p>Los capítulos estarán disponibles al abrir el manual.</p>`;return `<section class="cc-manual-grupo"><div class="cc-fila cc-fila-manual destacado"><button type="button" class="cc-documento cc-documento-accion" data-cc-id="${this.e(d.ID_Documento)}"><i class="fa-solid fa-book"></i><span><strong>${this.e(d.Titulo)}</strong><small>${this.e(d.Resumen)}</small><em>${this.e(d.Categoria)}</em></span></button><span class="cc-tipo">${this.e(this.etiquetaTipo(d.Tipo))}</span><span class="cc-version"><i class="fa-solid fa-code-branch"></i> ${this.e(d.Version_Actual)}</span><span class="cc-estado ${this.n(d.Estado).toLowerCase()}">${this.e(d.Estado)}</span><button type="button" class="cc-desplegar-manual" data-cc-toggle-manual aria-expanded="${abierto}"><i class="fa-solid fa-${abierto?"chevron-up":"list"}"></i><span>${abierto?"Ocultar":"Contenido"}</span></button></div><div class="cc-capitulos-manual" ${abierto?"":"hidden"}><header><strong>Contenido del manual</strong><span>Seleccione un capítulo para abrirlo</span></header>${capitulos}</div></section>`;},
 async abrirDocumento(id,idVersion){
  this.cargarEspera("Abriendo documento","Cargando contenido y recursos.");
  try{const r=await API.post({action:"obtenerDocumentoConocimiento",idDocumento:id,idVersion:idVersion||""});if(!r||!r.ok)throw new Error(r&&r.mensaje||"No fue posible abrir el documento.");this.modalDocumento(r.data);}catch(e){Sistema.error(e.message);}finally{this.ocultarEspera();}
 },
 modalDocumento(d){const x=d.documento||{},v=d.version||{},medios=d.multimedia||[],versiones=d.versiones||[];if(window.ManualAlmacenPT&&ManualAlmacenPT.existe(x.ID_Documento))v.Archivo_Principal_URL="";
  const cuerpo=`<section class="cc-detalle"><header class="cc-detalle-cabecera"><div><span>${this.e(this.etiquetaTipo(x.Tipo))} · ${this.e(x.Categoria)}</span><h2>${this.e(v.Titulo||x.Titulo)}</h2><p>${this.e(v.Resumen||x.Resumen)}</p></div><div class="cc-detalle-acciones">${d.puedeEditar?`<button id="ccEditar"><i class="fa-solid fa-pen"></i> Editar</button>`:""}<button id="ccCompartir"><i class="fa-solid fa-share-nodes"></i> Compartir</button></div></header><div class="cc-meta"><span>Versión ${this.e(v.Numero_Version)}</span><span>${this.e(v.Estado)}</span><span>${this.e(v.Fecha_Publicacion||v.Fecha_Creacion)}</span>${versiones.length>1?`<label>Historial <select id="ccVersion">${versiones.map(z=>`<option value="${this.e(z.ID_Version)}" ${String(z.ID_Version)===String(v.ID_Version)?"selected":""}>v${this.e(z.Numero_Version)} · ${this.e(z.Estado)} · ${this.e(z.Fecha_Creacion)}</option>`).join("")}</select></label>`:""}</div>${v.Archivo_Principal_URL?`<a class="cc-archivo" href="${this.url(v.Archivo_Principal_URL)}" target="_blank" rel="noopener"><i class="fa-solid fa-file-pdf"></i><span><strong>Abrir archivo principal</strong><small>Disponible en una pestaña nueva</small></span></a>`:""}<div class="cc-texto">${this.contenidoDocumento(x.ID_Documento,v.Contenido_Texto)}</div>${medios.length?`<section class="cc-recursos"><h3>Recursos del documento</h3><div>${medios.map(m=>this.recurso(m,d.puedeEditar)).join("")}</div></section>`:""}</section>`;
  Sistema.abrirModal("Centro de conocimiento",cuerpo,{clase:"modal-centro-conocimiento"});
  if(d.puedeEditar){const barra=document.querySelector(".cc-detalle-acciones");if(barra){const b=document.createElement("button");b.type="button";b.id="ccAdjuntar";b.innerHTML='<i class="fa-solid fa-paperclip"></i> Adjuntar';b.onclick=()=>this.abrirAdjunto(x,v);barra.insertBefore(b,document.getElementById("ccCompartir"));}}
  const editar=document.getElementById("ccEditar"),compartir=document.getElementById("ccCompartir"),sel=document.getElementById("ccVersion");if(editar)editar.onclick=()=>this.editarDocumento(d);if(sel)sel.onchange=()=>this.abrirDocumento(x.ID_Documento,sel.value);if(compartir)compartir.onclick=()=>this.compartir(x,v);document.querySelectorAll("[data-cc-eliminar-medio]").forEach(b=>b.onclick=()=>this.eliminarMedio(b.dataset.ccEliminarMedio,x.ID_Documento));
  if(window.ManualAlmacenPT&&ManualAlmacenPT.existe(x.ID_Documento))ManualAlmacenPT.vincular(this,x.ID_Documento,true);
 },
 recurso(m,editor){const tipo=this.n(m.Tipo_Medio),u=this.url(m.URL),vista=tipo==="IMAGEN"?`<img src="${u}" alt="${this.e(m.Titulo)}" loading="lazy">`:tipo==="AUDIO"?`<audio controls preload="metadata" src="${u}"></audio>`:tipo==="VIDEO"?`<video controls preload="metadata" src="${u}"></video>`:`<i class="fa-solid ${tipo==="PDF"?"fa-file-pdf":"fa-link"}"></i>`;return `<article class="cc-recurso">${vista}<div><strong>${this.e(m.Titulo)}</strong><p>${this.e(m.Descripcion)}</p><a href="${u}" target="_blank" rel="noopener">Abrir${this.n(m.Compartible)==="SI"?" / compartir":""}</a></div>${editor?`<button data-cc-eliminar-medio="${this.e(m.ID_Multimedia)}" title="Retirar recurso"><i class="fa-solid fa-trash"></i></button>`:""}</article>`;},
 editarDocumento(datos){const d=datos&&datos.documento||{},v=datos&&datos.version||{},roles=(d.Roles_Visibles||"TODOS").split(","),nuevo=!d.ID_Documento,contenidoInicial=window.ManualAlmacenPT&&ManualAlmacenPT.esContenidoInicial(d.ID_Documento,v.Contenido_Texto)?ManualAlmacenPT.textoEditable(d.ID_Documento):v.Contenido_Texto;
  const html=`<form id="ccForm" class="cc-editor"><input type="hidden" id="ccId" value="${this.e(d.ID_Documento)}"><div class="cc-grid"><label>Tipo<select id="ccEditTipo" required>${["MANUAL","POLITICA EMPRESA","POLITICA ALMACEN PT","PROCEDIMIENTO","TUTORIAL"].map(t=>`<option ${this.n(d.Tipo||"PROCEDIMIENTO")===t?"selected":""}>${t}</option>`).join("")}</select></label><label>Categoría<input id="ccCategoria" value="${this.e(d.Categoria)}" placeholder="Ej. Recepciones"></label><label class="cc-ancho">Título<input id="ccTitulo" value="${this.e(v.Titulo||d.Titulo)}" required></label><label class="cc-ancho">Resumen<input id="ccEditResumen" value="${this.e(v.Resumen||d.Resumen)}"></label><label class="cc-ancho">Contenido escrito<textarea id="ccContenido" rows="10" placeholder="Escriba el procedimiento, política o tutorial...">${this.e(contenidoInicial)}</textarea></label><label>Tipo de actualización<select id="ccTipoCambio"><option value="CORRECCION MENOR">Corrección de la versión actual</option><option value="NUEVA VERSION" ${nuevo?"selected":""}>Nueva versión</option></select></label><label>Número de versión<input id="ccNumeroVersion" value="${this.e(nuevo?"1.0":v.Numero_Version||d.Version_Actual)}" required></label><label class="cc-ancho">Descripción de cambios<textarea id="ccCambios" rows="2"></textarea></label><label class="cc-ancho">URL del archivo principal<input id="ccArchivoUrl" value="${this.e(v.Archivo_Principal_URL)}" placeholder="PDF o documento alojado"></label><label class="cc-ancho">Palabras clave<input id="ccPalabras" value="${this.e(d.Palabras_Clave)}" placeholder="Separadas por comas"></label></div><fieldset><legend>Visible para</legend><div class="cc-roles">${["TODOS"].concat(this.estado.roles||[]).filter((x,i,a)=>a.indexOf(x)===i).map(r=>`<label><input type="checkbox" data-cc-rol value="${this.e(r)}" ${roles.map(this.n).includes(this.n(r))?"checked":""}> ${this.e(r)}</label>`).join("")}</div></fieldset><label class="cc-check"><input id="ccDestacado" type="checkbox" ${Number(d.Destacado)?"checked":""}> Destacar en el catálogo</label><div class="cc-editor-botones"><button type="button" id="ccGuardarBorrador">Guardar borrador</button><button type="submit">Publicar y notificar</button></div></form>${!nuevo?`<section class="cc-subir"><h3>Agregar imagen, audio, video o PDF</h3><p>Primero guarde esta nueva versión; después podrá adjuntar recursos desde su vista.</p></section>`:""}`;
  Sistema.abrirModal(nuevo?"Nuevo contenido":"Editar contenido",html,{clase:"modal-centro-conocimiento modal-cc-editor"});
  document.getElementById("ccForm").onsubmit=e=>{e.preventDefault();this.guardarDocumento(true);};document.getElementById("ccGuardarBorrador").onclick=()=>this.guardarDocumento(false);
 },
 async guardarDocumento(publicar){const roles=[...document.querySelectorAll("[data-cc-rol]:checked")].map(x=>x.value);if(!roles.length){Sistema.info("Seleccione al menos un rol.");return;}const data={action:"guardarDocumentoConocimiento",idDocumento:document.getElementById("ccId").value,tipo:document.getElementById("ccEditTipo").value,categoria:document.getElementById("ccCategoria").value,titulo:document.getElementById("ccTitulo").value,resumen:document.getElementById("ccEditResumen").value,contenidoTexto:document.getElementById("ccContenido").value,tipoCambio:document.getElementById("ccTipoCambio").value,numeroVersion:document.getElementById("ccNumeroVersion").value,descripcionCambios:document.getElementById("ccCambios").value,archivoPrincipalUrl:document.getElementById("ccArchivoUrl").value,palabrasClave:document.getElementById("ccPalabras").value,rolesVisibles:roles,destacado:document.getElementById("ccDestacado").checked?"SI":"NO",publicar:publicar?"SI":"NO"};this.cargarEspera(publicar?"Publicando contenido":"Guardando borrador",publicar?"Creando la versión y notificando a sus destinatarios.":"Conservando los cambios sin enviar avisos.");try{const r=await API.post(data);if(!r||!r.ok)throw new Error(r&&r.mensaje||"No fue posible guardar.");Sistema.exito(r.mensaje);Sistema.cerrarModal&&Sistema.cerrarModal();await this.buscar(false);await this.abrirDocumento(r.data.idDocumento);}catch(e){Sistema.error(e.message);}finally{this.ocultarEspera();}},
 abrirAdjunto(doc,ver){Sistema.abrirModal("Agregar recurso",`<form id="ccFormAdjunto" class="cc-editor"><div class="cc-grid"><label>Tipo<select id="ccMedioTipo"><option>IMAGEN</option><option>AUDIO</option><option>VIDEO</option><option>PDF</option><option>ENLACE</option></select></label><label>Título<input id="ccMedioTitulo" required></label><label class="cc-ancho">Descripción<input id="ccMedioDescripcion"></label><label class="cc-ancho">Archivo (máximo 20 MB)<input id="ccMedioArchivo" type="file" accept="image/*,audio/*,video/*,application/pdf"></label><label class="cc-ancho">O indique una URL<input id="ccMedioUrl" type="url" placeholder="https://..."></label></div><label class="cc-check"><input id="ccMedioCompartible" type="checkbox"> Permitir acceso mediante enlace para compartir en móviles</label><div class="cc-editor-botones"><button type="submit">Guardar recurso</button></div></form>`,{clase:"modal-centro-conocimiento"});document.getElementById("ccFormAdjunto").onsubmit=e=>{e.preventDefault();this.guardarAdjunto(doc,ver);};},
 async guardarAdjunto(doc,ver){const archivo=document.getElementById("ccMedioArchivo").files[0],url=document.getElementById("ccMedioUrl").value;if(!archivo&&!url){Sistema.info("Seleccione un archivo o escriba una URL.");return;}if(archivo&&archivo.size>20*1024*1024){Sistema.info("El archivo supera 20 MB.");return;}this.cargarEspera("Guardando recurso","Subiendo y vinculando el archivo a esta versión.");try{const data={action:"guardarMultimediaConocimiento",idDocumento:doc.ID_Documento,idVersion:ver.ID_Version,tipoMedio:document.getElementById("ccMedioTipo").value,titulo:document.getElementById("ccMedioTitulo").value,descripcion:document.getElementById("ccMedioDescripcion").value,url:url,compartible:document.getElementById("ccMedioCompartible").checked?"SI":"NO"};if(archivo){data.archivoBase64=await this.base64(archivo);data.mimeType=archivo.type;data.nombreArchivo=archivo.name;}const r=await API.post(data);if(!r||!r.ok)throw new Error(r&&r.mensaje||"No fue posible guardar el recurso.");Sistema.exito(r.mensaje);await this.abrirDocumento(doc.ID_Documento,ver.ID_Version);}catch(e){Sistema.error(e.message);}finally{this.ocultarEspera();}},
 base64(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(",")[1]||"");r.onerror=rej;r.readAsDataURL(f);});},
 async eliminarMedio(id,doc){const ok=await Sistema.confirmar({titulo:"Retirar recurso",mensaje:"¿Desea retirar este recurso de la versión?",textoConfirmar:"Sí, retirar",textoCancelar:"Cancelar",tipo:"peligro"});if(!ok)return;this.cargarEspera("Retirando recurso","Actualizando la versión.");try{const r=await API.post({action:"eliminarMultimediaConocimiento",idMultimedia:id});if(!r||!r.ok)throw new Error(r&&r.mensaje||"No fue posible retirar el recurso.");Sistema.exito(r.mensaje);await this.abrirDocumento(doc);}catch(e){Sistema.error(e.message);}finally{this.ocultarEspera();}},
 compartir(d,v){const texto=`${d.Titulo} · versión ${v.Numero_Version}`,url=window.ManualAlmacenPT&&ManualAlmacenPT.existe(d.ID_Documento)?new URL(ManualAlmacenPT.pdf,location.href).href:(v.Archivo_Principal_URL||location.href);if(navigator.share){navigator.share({title:d.Titulo,text:texto,url:url}).catch(()=>{});return;}navigator.clipboard.writeText(url).then(()=>Sistema.exito("Enlace copiado.")).catch(()=>Sistema.info("Abra el archivo principal para compartirlo."));},
 etiquetaTipo(v){return String(v||"").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());},icono(v){const k=this.n(v);return k==="TUTORIAL"?"fa-circle-play":k==="MANUAL"?"fa-book":k.includes("POLITICA")?"fa-scale-balanced":"fa-list-check";},contenidoDocumento(id,v){return window.ManualAlmacenPT&&ManualAlmacenPT.existe(id)&&ManualAlmacenPT.esContenidoInicial(id,v)?ManualAlmacenPT.render(id):this.parrafos(v);},parrafos(v){return String(v||"").split(/\n{2,}/).map(p=>`<p>${this.e(p).replace(/\n/g,"<br>")}</p>`).join("")||"<p>Este documento no tiene contenido escrito.</p>";},url(v){const s=String(v||"").trim();return /^(https?:|\.\.\/|\/)/i.test(s)?this.e(s):"#";},n(v){return String(v||"").trim().normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase();},e(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");},debounce(fn,ms){let t;return()=>{clearTimeout(t);t=setTimeout(fn,ms);};},cargarEspera(t,m){if(window.CargadorSistema)CargadorSistema.mostrar(t,m);},ocultarEspera(){if(window.CargadorSistema)CargadorSistema.ocultar();}
};
